version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - VUE_APP_API_URL=http://35.207.254.40:443/api
      - VUE_APP_FILE_URL=http://35.207.254.40:443/uploads/

  server:
    build: ./server
    ports:
      - "443:3000"
    environment:
      - DATABASE=mongodb://10.132.0.2:27017/THOMAS
      - CORS_ORIGIN=http://35.207.254.40
      - NODE_ENV=development
      - JWT_SECRET=secret-token-rahasia-gw
      - PORT=3000
    volumes:
      - /home/toalber231/data-uploads:/app/uploads
